INSERT INTO CUSTOMERS(ID, NAME) VALUES (1, 'Tom1');
INSERT INTO CUSTOMERS(ID, NAME) VALUES (2, 'Tom2');
INSERT INTO CUSTOMERS(ID, NAME) VALUES (3, 'Tom3');
INSERT INTO CUSTOMERS(ID, NAME) VALUES (4, 'Tom4');
INSERT INTO CUSTOMERS(ID, NAME) VALUES (5, 'Tom5');